[
  ./globals.nix
  ./bitcoind.nix
  ./bitcoincashd.nix
  ./dashd.nix
  ./rabbitmq.nix
  ./elasticsearch.nix
  ./elasticsearch-curator.nix
  ./redis.nix
  ./nginx.nix
  ./deployer.nix
  ./etcd-operator.nix
  ./etcd.nix
  ./rippled.nix
  ./zetcd.nix
  ./kibana.nix
  ./parity.nix
  ./beehive.nix
  ./minio.nix
  ./grafana.nix
  ./galera.nix
  ./kube-lego.nix
  ./pachyderm.nix
  ./vault.nix
  ./vault-ui.nix
  ./vault-controller.nix
  ./vault-login.nix
  ./logstash.nix
  ./mariadb.nix
  ./influxdb.nix
  ./kubelog.nix
  ./secret-restart-controller.nix
  ./k8s-request-cert.nix
  ./selfsigned-cert-deployer.nix
  ./nginx-ingress.nix
  ./external-dns.nix
  ./mongo.nix
  ./pritunl.nix
  ./cloud-sql-proxy.nix
  ./mediawiki.nix
  ./k8s-snapshot.nix
  ./goldfish.nix
  ./zookeeper.nix
  ./kafka.nix
  ./ksql.nix
  ./argo-ingress-controller.nix
  ./ambassador.nix
] ++ import ./prometheus/module-list.nix
