[
  ./rabbitmq.nix
  ./elasticsearch.nix
  ./elasticsearch-curator.nix
  ./redis.nix
  ./nginx.nix
  ./deployer.nix
  ./etcd-operator.nix
  ./etcd.nix
  ./rippled.nix
  ./zetcd.nix
  ./kibana.nix
  ./parity.nix
  ./beehive.nix
  ./minio.nix
  ./prometheus.nix
  ./grafana.nix
  ./prometheus-kubernetes.nix
  ./galera.nix
  ./kube-lego.nix
  ./pachyderm.nix
  ./vault.nix
  ./vault-ui.nix
  ./vault-controller.nix
  ./vault-login.nix
  ./logstash.nix
  ./mariadb.nix
  ./influxdb.nix
  ./kubelog.nix
  ./secret-restart-controller.nix
  ./k8s-request-cert.nix
  ./selfsigned-cert-deployer.nix
]
