[
  ./rabbitmq/default.nix
  ./elasticsearch.nix
  ./elasticsearch-curator.nix
  ./redis.nix
  ./nginx.nix
  ./galera/default.nix
  ./deployer.nix
  ./etcd.nix
  ./rippled.nix
  ./zetcd.nix
  ./kibana.nix
  ./parity.nix
]
